- name: priority:high
  description: This is a high priority
  color: e99695
- name: priority:medium
  description: This is a medium priority
  color: fef2c0
- name: priority:low
  description: This is a low priority
  color: c2e0c6