default_language_version:
  python: python3.10

default_stages: [commit, push]

repos:
  - repo: local
    hooks:
    - id: lint
      name: Lint
      stages: [commit]
      language: system
      entry: make pre-commit
    - id: test
      name: Test
      stages: [push]
      language: system
      entry: make pre-push
