# This file contains values from Cookiecutter

default_context:
  project_name: "roc"
  project_description: "Reinforcement Learning of Concepts"
  organization: "apowers313"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "apowers313"
  email: "apowers@ato.ms"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "none"
