name: Build

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          make uv-download

      - name: Set up cache
        uses: actions/cache@v3.3.1
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('uv.lock') }}

      - name: Install dependencies
        run: |
          make install
      - name: Run safety checks
        run: |
          make check-safety

      - name: Run style checks
        run: |
          make check-codestyle

  build:
    needs: lint

    runs-on: ubuntu-latest

    services:
      mg:
        image: ghcr.io/apowers313/roc-dev:1.3.2
        ports:
          - 7687:7687

    strategy:
      matrix:
        # TODO: try uv install on mac and windows
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up cache
        uses: actions/cache@v3.3.1
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('uv.lock') }}

      - name: Install uv
        run: |
          make uv-download

      - name: Install dependencies
        run: |
          make install

      # - name: Load database test data
      #   run: |
      #     make load-data

      - name: Run tests
        run: |
          make test

      - name: Build coverage
        run: |
          make coverage

      - name: Publish Coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.lcov

      - name: Docs build
        run: |
          make docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
